- name: Deploy to ec2
  hosts: localhost
  connection: local

  tasks:
    - name: Locate running EC2 instances
      ec2_instance_info:
        region: us-east-1
        aws_access_key: ASIASFON62WFL4WS2YJY
        aws_secret_key: 4t8Bi60xJnLMqfWrFDezyYs0Dzy5+BkPNiqYVU6M
        security_token: FwoGZXIvYXdzEBgaDFqHZdEd2U24PLUj4yLIAf69n6XjbmjbBtmOiRPmEAyHgCe52QIdSFqdcHpUm0Uwjd179RuWZIzHIJyuyYdhj0oDgOXCq1NOzU8lHFPOoXiGHVC5Fv8+8NM0Zd3s+9XwgCZkvFUiAeDlN2yUoeZCrIK+l/vrw87/jfdPfHv2RuxMy5bBuZmphxrjxqMv1/N0+jIH5dtRpUopUH6je+vTzPpF3aEEU/qt45fEC0+T9dZjEpp1ciIXiCd/8V7ELIQ1AVl5SY3gJkTMrNdfq646sRdZWsjS//O6KOPiif8FMi1W8bULly9i4zq2EyccnDcdrJu57j8NvwroJb0uBGvyN2DfcsdLRV8DBArwFaE=
      register: info

    - name: Launch EC2 instance
      ec2:
        instance_type: t2.small
        image: ami-00ddb0e5626798373
        region: us-east-1
        key_name: key2
        vpc_subnet_id: subnet-d70c8d88
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: ASIASFON62WFL4WS2YJY
        aws_secret_key: 4t8Bi60xJnLMqfWrFDezyYs0Dzy5+BkPNiqYVU6M
        security_token: FwoGZXIvYXdzEBgaDFqHZdEd2U24PLUj4yLIAf69n6XjbmjbBtmOiRPmEAyHgCe52QIdSFqdcHpUm0Uwjd179RuWZIzHIJyuyYdhj0oDgOXCq1NOzU8lHFPOoXiGHVC5Fv8+8NM0Zd3s+9XwgCZkvFUiAeDlN2yUoeZCrIK+l/vrw87/jfdPfHv2RuxMy5bBuZmphxrjxqMv1/N0+jIH5dtRpUopUH6je+vTzPpF3aEEU/qt45fEC0+T9dZjEpp1ciIXiCd/8V7ELIQ1AVl5SY3gJkTMrNdfq646sRdZWsjS//O6KOPiif8FMi1W8bULly9i4zq2EyccnDcdrJu57j8NvwroJb0uBGvyN2DfcsdLRV8DBArwFaE=
      register: ec2

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh
  
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
     
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from git
      git:
        repo: 'https://github.com/dolotinaelvira/repository.git'
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run Docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 90
      poll: 0
      become: yes
    - wait_for:
        port: 80

- name: Terminate instances
  hosts: localhost
  connection: local

  tasks:
    - name: Terminate previous instances
      ec2:
        region: us-east-1
        state: 'absent'
        instance_ids: '{{ item.instance_id }}'
        aws_access_key: ASIASFON62WFL4WS2YJY
        aws_secret_key: 4t8Bi60xJnLMqfWrFDezyYs0Dzy5+BkPNiqYVU6M
        security_token: FwoGZXIvYXdzEBgaDFqHZdEd2U24PLUj4yLIAf69n6XjbmjbBtmOiRPmEAyHgCe52QIdSFqdcHpUm0Uwjd179RuWZIzHIJyuyYdhj0oDgOXCq1NOzU8lHFPOoXiGHVC5Fv8+8NM0Zd3s+9XwgCZkvFUiAeDlN2yUoeZCrIK+l/vrw87/jfdPfHv2RuxMy5bBuZmphxrjxqMv1/N0+jIH5dtRpUopUH6je+vTzPpF3aEEU/qt45fEC0+T9dZjEpp1ciIXiCd/8V7ELIQ1AVl5SY3gJkTMrNdfq646sRdZWsjS//O6KOPiif8FMi1W8bULly9i4zq2EyccnDcdrJu57j8NvwroJb0uBGvyN2DfcsdLRV8DBArwFaE=

      loop: "{{ info.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"
