- name: Deploy to ec2
  hosts: localhost
  connection: local

  tasks:
    - name: Locate running EC2 instances
      ec2_instance_info:
        region: us-east-1
        aws_access_key: ASIASHM24H7QY4N6NLRT
        aws_secret_key: jVhT54LNnm+lej2ZpOBIxdPxCCW0saKL5y9Hg0Ha
        security_token: FwoGZXIvYXdzEBcaDM0y0ZrK3C2QdsDOTyLBAeqJcchHr+J9UcjzZRrY4T+7eijavA4owmXxKQQht8s+PgAFuZ8qas01wMcNTRUQ+7NstMYE9YceF/T2E0fLPY4jx5akWixzQ3wapITbafrEmmobt3ydwBI3itjFqR4M4SY0IQ1jYXT/KjvkzJNRzxTYA2dJfihM5thj2r4b4OcGMzznb2zd3ca8Wz4gYRJocM50DiwTp8W47n3tLtIv1BlKFMlV132V6Z20u1bVkFHAzRCJP92j0dyxjnRFjTSawHkoiMOJ/wUyLReyp+mVXGFJ9GXolzzVRosGrQU1YibomjNqA0OXq8QIEPCZsoRto0GiZEMyow==
      register: info

    - name: Launch EC2 instance
      ec2:
        instance_type: t2.small
        image: ami-00ddb0e5626798373
        region: us-east-1
        key_name: key2
        vpc_subnet_id: subnet-d70c8d88
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: ASIASHM24H7QY4N6NLRT
        aws_secret_key: jVhT54LNnm+lej2ZpOBIxdPxCCW0saKL5y9Hg0Ha
        security_token: FwoGZXIvYXdzEBcaDM0y0ZrK3C2QdsDOTyLBAeqJcchHr+J9UcjzZRrY4T+7eijavA4owmXxKQQht8s+PgAFuZ8qas01wMcNTRUQ+7NstMYE9YceF/T2E0fLPY4jx5akWixzQ3wapITbafrEmmobt3ydwBI3itjFqR4M4SY0IQ1jYXT/KjvkzJNRzxTYA2dJfihM5thj2r4b4OcGMzznb2zd3ca8Wz4gYRJocM50DiwTp8W47n3tLtIv1BlKFMlV132V6Z20u1bVkFHAzRCJP92j0dyxjnRFjTSawHkoiMOJ/wUyLReyp+mVXGFJ9GXolzzVRosGrQU1YibomjNqA0OXq8QIEPCZsoRto0GiZEMyow==
      register: ec2

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'

- name: Configure EC2
  hosts: launched
  connection: ssh
  
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
     
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from git
      git:
        repo: 'https://github.com/dolotinaelvira/semestralka-devops.git'
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run Docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 90
      poll: 0
      become: yes
    - wait_for:
        port: 80

- name: Terminate instances
  hosts: localhost
  connection: local

  tasks:
    - name: Terminate previous instances
      ec2:
        region: us-east-1
        state: 'absent'
        instance_ids: '{{ item.instance_id }}'
        aws_access_key: ASIASHM24H7QY4N6NLRT
        aws_secret_key: jVhT54LNnm+lej2ZpOBIxdPxCCW0saKL5y9Hg0Ha
        security_token: FwoGZXIvYXdzEBcaDM0y0ZrK3C2QdsDOTyLBAeqJcchHr+J9UcjzZRrY4T+7eijavA4owmXxKQQht8s+PgAFuZ8qas01wMcNTRUQ+7NstMYE9YceF/T2E0fLPY4jx5akWixzQ3wapITbafrEmmobt3ydwBI3itjFqR4M4SY0IQ1jYXT/KjvkzJNRzxTYA2dJfihM5thj2r4b4OcGMzznb2zd3ca8Wz4gYRJocM50DiwTp8W47n3tLtIv1BlKFMlV132V6Z20u1bVkFHAzRCJP92j0dyxjnRFjTSawHkoiMOJ/wUyLReyp+mVXGFJ9GXolzzVRosGrQU1YibomjNqA0OXq8QIEPCZsoRto0GiZEMyow==

      loop: "{{ info.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"
